<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-21T12:33:32 IST" name="Default suite" finished-at="2021-09-21T12:33:44 IST" duration-ms="11891">
    <groups>
    </groups>
    <test started-at="2021-09-21T12:33:32 IST" name="Default test" finished-at="2021-09-21T12:33:44 IST" duration-ms="11891">
      <class name="com.crm.PurchaseOrderApproved.TC_06_CreateSubject">
        <test-method is-config="true" signature="ConnectDB()[pri:0, instance:com.crm.PurchaseOrderApproved.TC_06_CreateSubject@4f80542f]" started-at="2021-09-21T12:33:32 IST" name="ConnectDB" finished-at="2021-09-21T12:33:32 IST" duration-ms="737" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConnectDB -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.crm.PurchaseOrderApproved.TC_06_CreateSubject@4f80542f]" started-at="2021-09-21T12:33:32 IST" name="launchBrowser" finished-at="2021-09-21T12:33:43 IST" duration-ms="10146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="CreateSubjectWithMultipleData(java.lang.String,java.lang.String)[pri:0, instance:com.crm.PurchaseOrderApproved.TC_06_CreateSubject@4f80542f]" started-at="2021-09-21T12:33:43 IST" name="CreateSubjectWithMultipleData" data-provider="getData" finished-at="2021-09-21T12:33:44 IST" duration-ms="1495" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void com.crm.PurchaseOrderApproved.TC_06_CreateSubject.CreateSubjectWithMultipleData(java.lang.String,java.lang.String) throws java.lang.Throwable] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: CreateSubjectWithMultipleData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Tc_01,(java.lang.String) CreatePurchaseOrder,(java.lang.String) Approved,(java.lang.String) Created,(java.lang.String) Delivered,(java.lang.String) Cancelled,(java.lang.String) Received Shipment]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.crm.PurchaseOrderApproved.TC_06_CreateSubject.CreateSubjectWithMultipleData(java.lang.String,java.lang.String) throws java.lang.Throwable] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: CreateSubjectWithMultipleData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Tc_01,(java.lang.String) CreatePurchaseOrder,(java.lang.String) Approved,(java.lang.String) Created,(java.lang.String) Delivered,(java.lang.String) Cancelled,(java.lang.String) Received Shipment]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateSubjectWithMultipleData -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.crm.PurchaseOrderApproved.TC_06_CreateSubject@4f80542f]" started-at="2021-09-21T12:33:44 IST" name="closeBrowser" finished-at="2021-09-21T12:33:44 IST" duration-ms="206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeDB()[pri:0, instance:com.crm.PurchaseOrderApproved.TC_06_CreateSubject@4f80542f]" started-at="2021-09-21T12:33:44 IST" name="closeDB" finished-at="2021-09-21T12:33:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDB -->
      </class> <!-- com.crm.PurchaseOrderApproved.TC_06_CreateSubject -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
